version: "3"
services:
  webserver:
    build:
      context: ./bin
    volumes:
      - ${APP_ROOT-./master}:/var/www/html:rw
      - ${VHOST_CONFIG-./config/000-default.conf}:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - 8080:80
